/**
 * Consistent error codes for API responses.
 * Frontend can match on `code` instead of parsing error strings.
 */
export const ErrorCode = {
  // Auth
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",

  // Validation
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INVALID_JSON: "INVALID_JSON",
  REQUEST_TOO_LARGE: "REQUEST_TOO_LARGE",

  // Rate limiting
  RATE_LIMITED: "RATE_LIMITED",

  // Resources
  NOT_FOUND: "NOT_FOUND",
  VERSION_CONFLICT: "VERSION_CONFLICT",

  // Plan limits
  PROJECT_LIMIT: "PROJECT_LIMIT",
  EXPORT_LIMIT: "EXPORT_LIMIT",
  PLAN_REQUIRED: "PLAN_REQUIRED",
  PRO_FEATURE: "PRO_FEATURE",

  // Stripe
  PRICE_NOT_CONFIGURED: "PRICE_NOT_CONFIGURED",
  NO_SUBSCRIPTION: "NO_SUBSCRIPTION",

  // Password reset
  INVALID_RESET_TOKEN: "INVALID_RESET_TOKEN",

  // Backtest
  DUPLICATE_UPLOAD: "DUPLICATE_UPLOAD",
  PARSE_FAILED: "PARSE_FAILED",
  ANALYSIS_EXISTS: "ANALYSIS_EXISTS",

  // Baseline linking
  BASELINE_ALREADY_LINKED: "BASELINE_ALREADY_LINKED",
  INELIGIBLE_INSTANCE: "INELIGIBLE_INSTANCE",
  INELIGIBLE_BACKTEST: "INELIGIBLE_BACKTEST",

  // Operator hold
  STRATEGY_HALTED: "STRATEGY_HALTED",

  // Override workflow
  OVERRIDE_CONFLICT: "OVERRIDE_CONFLICT",
  OVERRIDE_NOT_FOUND: "OVERRIDE_NOT_FOUND",
  OVERRIDE_EXPIRED: "OVERRIDE_EXPIRED",
  OVERRIDE_POLICY_VIOLATION: "OVERRIDE_POLICY_VIOLATION",

  // Service availability
  AI_UNAVAILABLE: "AI_UNAVAILABLE",

  // Telemetry
  MISSING_API_KEY: "MISSING_API_KEY",
  INVALID_API_KEY: "INVALID_API_KEY",
  INVALID_CONTENT_TYPE: "INVALID_CONTENT_TYPE",
  CHAIN_VERIFICATION_FAILED: "CHAIN_VERIFICATION_FAILED",
  DUPLICATE_EVENT: "DUPLICATE_EVENT",
  TRANSACTION_CONFLICT: "TRANSACTION_CONFLICT",

  // Generic
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

/** Helper to create a consistent error response body */
export function apiError(code: ErrorCode, message: string, details?: string | string[]) {
  return {
    error: message,
    code,
    ...(details ? { details } : {}),
  };
}
