import type { BuildJsonSchema } from "@/types/builder";
import type { PlanTier } from "./plans";

export interface StrategyPreset {
  id: string;
  name: string;
  description: string;
  tier: PlanTier;
  buildJson: BuildJsonSchema;
}

const now = new Date().toISOString();
const meta = { createdAt: now, updatedAt: now };

export const STRATEGY_PRESETS: StrategyPreset[] = [
  {
    id: "ma-crossover",
    name: "MA Crossover",
    description:
      "Classic moving average crossover strategy using a fast (10) and slow (50) EMA. Buys when fast crosses above slow, sells when fast crosses below.",
    tier: "FREE",
    buildJson: {
      version: "1.0",
      nodes: [
        {
          id: "timing1",
          type: "always",
          position: { x: 300, y: 0 },
          data: {
            label: "Always",
            category: "timing",
            timingType: "always",
          },
        },
        {
          id: "ma-fast",
          type: "moving-average",
          position: { x: 100, y: 180 },
          data: {
            label: "Fast MA (10)",
            category: "indicator",
            indicatorType: "moving-average",
            timeframe: "H1",
            period: 10,
            method: "EMA",
            signalMode: "every_tick",
            shift: 0,
          },
        },
        {
          id: "ma-slow",
          type: "moving-average",
          position: { x: 550, y: 180 },
          data: {
            label: "Slow MA (50)",
            category: "indicator",
            indicatorType: "moving-average",
            timeframe: "H1",
            period: 50,
            method: "EMA",
            signalMode: "every_tick",
            shift: 0,
          },
        },
        {
          id: "buy1",
          type: "place-buy",
          position: { x: 100, y: 360 },
          data: {
            label: "Place Buy",
            category: "trading",
            tradingType: "place-buy",
            method: "FIXED_LOT",
            fixedLot: 0.1,
            riskPercent: 2,
            minLot: 0.01,
            maxLot: 10,
          },
        },
        {
          id: "sell1",
          type: "place-sell",
          position: { x: 550, y: 360 },
          data: {
            label: "Place Sell",
            category: "trading",
            tradingType: "place-sell",
            method: "FIXED_LOT",
            fixedLot: 0.1,
            riskPercent: 2,
            minLot: 0.01,
            maxLot: 10,
          },
        },
        {
          id: "sl-buy",
          type: "stop-loss",
          position: { x: 0, y: 540 },
          data: {
            label: "Buy Stoploss",
            category: "trading",
            tradingType: "stop-loss",
            method: "FIXED_PIPS",
            fixedPips: 50,
            atrMultiplier: 1.5,
            atrPeriod: 14,
          },
        },
        {
          id: "tp-buy",
          type: "take-profit",
          position: { x: 200, y: 540 },
          data: {
            label: "Buy Take Profit",
            category: "trading",
            tradingType: "take-profit",
            method: "RISK_REWARD",
            fixedPips: 100,
            riskRewardRatio: 2,
            atrMultiplier: 3,
            atrPeriod: 14,
          },
        },
        {
          id: "sl-sell",
          type: "stop-loss",
          position: { x: 450, y: 540 },
          data: {
            label: "Sell Stoploss",
            category: "trading",
            tradingType: "stop-loss",
            method: "FIXED_PIPS",
            fixedPips: 50,
            atrMultiplier: 1.5,
            atrPeriod: 14,
          },
        },
        {
          id: "tp-sell",
          type: "take-profit",
          position: { x: 650, y: 540 },
          data: {
            label: "Sell Take Profit",
            category: "trading",
            tradingType: "take-profit",
            method: "RISK_REWARD",
            fixedPips: 100,
            riskRewardRatio: 2,
            atrMultiplier: 3,
            atrPeriod: 14,
          },
        },
      ],
      edges: [
        { id: "e1", source: "timing1", target: "ma-fast" },
        { id: "e2", source: "timing1", target: "ma-slow" },
        { id: "e3", source: "ma-fast", target: "buy1" },
        { id: "e4", source: "ma-slow", target: "sell1" },
        { id: "e5", source: "buy1", target: "sl-buy" },
        { id: "e6", source: "buy1", target: "tp-buy" },
        { id: "e7", source: "sell1", target: "sl-sell" },
        { id: "e8", source: "sell1", target: "tp-sell" },
      ],
      viewport: { x: 0, y: 0, zoom: 0.8 },
      metadata: meta,
      settings: {
        magicNumber: 100001,
        comment: "MA Crossover",
        maxOpenTrades: 1,
        allowHedging: false,
        maxTradesPerDay: 0,
      },
    } as BuildJsonSchema,
  },
  {
    id: "rsi-mean-reversion",
    name: "RSI Mean Reversion",
    description:
      "Mean reversion strategy trading RSI oversold/overbought levels during the London session. Buys when RSI crosses above 30, sells when RSI crosses below 70.",
    tier: "FREE",
    buildJson: {
      version: "1.0",
      nodes: [
        {
          id: "timing1",
          type: "trading-session",
          position: { x: 300, y: 0 },
          data: {
            label: "London Session",
            category: "timing",
            timingType: "trading-session",
            session: "LONDON",
            tradeMondayToFriday: true,
          },
        },
        {
          id: "rsi1",
          type: "rsi",
          position: { x: 300, y: 180 },
          data: {
            label: "RSI (14)",
            category: "indicator",
            indicatorType: "rsi",
            timeframe: "H1",
            period: 14,
            signalMode: "every_tick",
            overboughtLevel: 70,
            oversoldLevel: 30,
          },
        },
        {
          id: "buy1",
          type: "place-buy",
          position: { x: 100, y: 360 },
          data: {
            label: "Place Buy",
            category: "trading",
            tradingType: "place-buy",
            method: "FIXED_LOT",
            fixedLot: 0.1,
            riskPercent: 2,
            minLot: 0.01,
            maxLot: 10,
          },
        },
        {
          id: "sell1",
          type: "place-sell",
          position: { x: 550, y: 360 },
          data: {
            label: "Place Sell",
            category: "trading",
            tradingType: "place-sell",
            method: "FIXED_LOT",
            fixedLot: 0.1,
            riskPercent: 2,
            minLot: 0.01,
            maxLot: 10,
          },
        },
        {
          id: "sl-buy",
          type: "stop-loss",
          position: { x: 0, y: 540 },
          data: {
            label: "Buy Stoploss",
            category: "trading",
            tradingType: "stop-loss",
            method: "FIXED_PIPS",
            fixedPips: 30,
            atrMultiplier: 1.5,
            atrPeriod: 14,
          },
        },
        {
          id: "tp-buy",
          type: "take-profit",
          position: { x: 200, y: 540 },
          data: {
            label: "Buy Take Profit",
            category: "trading",
            tradingType: "take-profit",
            method: "FIXED_PIPS",
            fixedPips: 60,
            riskRewardRatio: 2,
            atrMultiplier: 3,
            atrPeriod: 14,
          },
        },
        {
          id: "sl-sell",
          type: "stop-loss",
          position: { x: 450, y: 540 },
          data: {
            label: "Sell Stoploss",
            category: "trading",
            tradingType: "stop-loss",
            method: "FIXED_PIPS",
            fixedPips: 30,
            atrMultiplier: 1.5,
            atrPeriod: 14,
          },
        },
        {
          id: "tp-sell",
          type: "take-profit",
          position: { x: 650, y: 540 },
          data: {
            label: "Sell Take Profit",
            category: "trading",
            tradingType: "take-profit",
            method: "FIXED_PIPS",
            fixedPips: 60,
            riskRewardRatio: 2,
            atrMultiplier: 3,
            atrPeriod: 14,
          },
        },
      ],
      edges: [
        { id: "e1", source: "timing1", target: "rsi1" },
        { id: "e2", source: "rsi1", target: "buy1" },
        { id: "e3", source: "rsi1", target: "sell1" },
        { id: "e4", source: "buy1", target: "sl-buy" },
        { id: "e5", source: "buy1", target: "tp-buy" },
        { id: "e6", source: "sell1", target: "sl-sell" },
        { id: "e7", source: "sell1", target: "tp-sell" },
      ],
      viewport: { x: 0, y: 0, zoom: 0.8 },
      metadata: meta,
      settings: {
        magicNumber: 100002,
        comment: "RSI Mean Reversion",
        maxOpenTrades: 1,
        allowHedging: false,
        maxTradesPerDay: 0,
      },
    } as BuildJsonSchema,
  },
  {
    id: "breakout-strategy",
    name: "Breakout Strategy",
    description:
      "Breakout strategy trading the Asian session range during custom weekday hours (8-17). Uses ATR-based stop loss and 1.5:1 risk-reward take profit.",
    tier: "FREE",
    buildJson: {
      version: "1.0",
      nodes: [
        {
          id: "timing1",
          type: "custom-times",
          position: { x: 300, y: 0 },
          data: {
            label: "Weekday Hours",
            category: "timing",
            timingType: "custom-times",
            days: {
              monday: true,
              tuesday: true,
              wednesday: true,
              thursday: true,
              friday: true,
              saturday: false,
              sunday: false,
            },
            timeSlots: [{ startHour: 8, startMinute: 0, endHour: 17, endMinute: 0 }],
          },
        },
        {
          id: "rb1",
          type: "range-breakout",
          position: { x: 300, y: 180 },
          data: {
            label: "Asian Range Breakout",
            category: "priceaction",
            priceActionType: "range-breakout",
            timeframe: "H1",
            rangeType: "SESSION",
            lookbackCandles: 20,
            rangeSession: "ASIAN",
            sessionStartHour: 0,
            sessionStartMinute: 0,
            sessionEndHour: 8,
            sessionEndMinute: 0,
            breakoutDirection: "BOTH",
            entryMode: "ON_CLOSE",
            bufferPips: 2,
            minRangePips: 10,
            maxRangePips: 0,
          },
        },
        {
          id: "buy1",
          type: "place-buy",
          position: { x: 100, y: 360 },
          data: {
            label: "Place Buy",
            category: "trading",
            tradingType: "place-buy",
            method: "FIXED_LOT",
            fixedLot: 0.1,
            riskPercent: 2,
            minLot: 0.01,
            maxLot: 10,
          },
        },
        {
          id: "sell1",
          type: "place-sell",
          position: { x: 550, y: 360 },
          data: {
            label: "Place Sell",
            category: "trading",
            tradingType: "place-sell",
            method: "FIXED_LOT",
            fixedLot: 0.1,
            riskPercent: 2,
            minLot: 0.01,
            maxLot: 10,
          },
        },
        {
          id: "sl-buy",
          type: "stop-loss",
          position: { x: 0, y: 540 },
          data: {
            label: "Buy ATR Stoploss",
            category: "trading",
            tradingType: "stop-loss",
            method: "ATR_BASED",
            fixedPips: 50,
            atrMultiplier: 1.5,
            atrPeriod: 14,
          },
        },
        {
          id: "tp-buy",
          type: "take-profit",
          position: { x: 200, y: 540 },
          data: {
            label: "Buy Take Profit",
            category: "trading",
            tradingType: "take-profit",
            method: "RISK_REWARD",
            fixedPips: 100,
            riskRewardRatio: 1.5,
            atrMultiplier: 3,
            atrPeriod: 14,
          },
        },
        {
          id: "sl-sell",
          type: "stop-loss",
          position: { x: 450, y: 540 },
          data: {
            label: "Sell ATR Stoploss",
            category: "trading",
            tradingType: "stop-loss",
            method: "ATR_BASED",
            fixedPips: 50,
            atrMultiplier: 1.5,
            atrPeriod: 14,
          },
        },
        {
          id: "tp-sell",
          type: "take-profit",
          position: { x: 650, y: 540 },
          data: {
            label: "Sell Take Profit",
            category: "trading",
            tradingType: "take-profit",
            method: "RISK_REWARD",
            fixedPips: 100,
            riskRewardRatio: 1.5,
            atrMultiplier: 3,
            atrPeriod: 14,
          },
        },
      ],
      edges: [
        { id: "e1", source: "timing1", target: "rb1" },
        { id: "e2", source: "rb1", target: "buy1" },
        { id: "e3", source: "rb1", target: "sell1" },
        { id: "e4", source: "buy1", target: "sl-buy" },
        { id: "e5", source: "buy1", target: "tp-buy" },
        { id: "e6", source: "sell1", target: "sl-sell" },
        { id: "e7", source: "sell1", target: "tp-sell" },
      ],
      viewport: { x: 0, y: 0, zoom: 0.8 },
      metadata: meta,
      settings: {
        magicNumber: 100003,
        comment: "Breakout Strategy",
        maxOpenTrades: 1,
        allowHedging: false,
        maxTradesPerDay: 0,
      },
    } as BuildJsonSchema,
  },
  {
    id: "bb-squeeze",
    name: "BB Squeeze",
    description:
      "Bollinger Bands squeeze strategy with ADX trend filter during the London session. Buys when price touches the lower band in a trending market, sells when price touches the upper band.",
    tier: "FREE",
    buildJson: {
      version: "1.0",
      nodes: [
        {
          id: "timing1",
          type: "trading-session",
          position: { x: 300, y: 0 },
          data: {
            label: "London Session",
            category: "timing",
            timingType: "trading-session",
            session: "LONDON",
            tradeMondayToFriday: true,
          },
        },
        {
          id: "bb1",
          type: "bollinger-bands",
          position: { x: 100, y: 180 },
          data: {
            label: "Bollinger Bands (20, 2)",
            category: "indicator",
            indicatorType: "bollinger-bands",
            timeframe: "H1",
            period: 20,
            deviation: 2,
            shift: 0,
            signalMode: "candle_close",
          },
        },
        {
          id: "adx1",
          type: "adx",
          position: { x: 550, y: 180 },
          data: {
            label: "ADX (14)",
            category: "indicator",
            indicatorType: "adx",
            timeframe: "H1",
            period: 14,
            trendLevel: 25,
            signalMode: "candle_close",
          },
        },
        {
          id: "buy1",
          type: "place-buy",
          position: { x: 100, y: 360 },
          data: {
            label: "Place Buy",
            category: "trading",
            tradingType: "place-buy",
            method: "RISK_PERCENT",
            fixedLot: 0.1,
            riskPercent: 2,
            minLot: 0.01,
            maxLot: 10,
          },
        },
        {
          id: "sell1",
          type: "place-sell",
          position: { x: 550, y: 360 },
          data: {
            label: "Place Sell",
            category: "trading",
            tradingType: "place-sell",
            method: "RISK_PERCENT",
            fixedLot: 0.1,
            riskPercent: 2,
            minLot: 0.01,
            maxLot: 10,
          },
        },
        {
          id: "sl-buy",
          type: "stop-loss",
          position: { x: 0, y: 540 },
          data: {
            label: "Buy ATR Stoploss",
            category: "trading",
            tradingType: "stop-loss",
            method: "ATR_BASED",
            fixedPips: 50,
            atrMultiplier: 2,
            atrPeriod: 14,
          },
        },
        {
          id: "tp-buy",
          type: "take-profit",
          position: { x: 200, y: 540 },
          data: {
            label: "Buy Take Profit",
            category: "trading",
            tradingType: "take-profit",
            method: "RISK_REWARD",
            fixedPips: 100,
            riskRewardRatio: 2,
            atrMultiplier: 3,
            atrPeriod: 14,
          },
        },
        {
          id: "sl-sell",
          type: "stop-loss",
          position: { x: 450, y: 540 },
          data: {
            label: "Sell ATR Stoploss",
            category: "trading",
            tradingType: "stop-loss",
            method: "ATR_BASED",
            fixedPips: 50,
            atrMultiplier: 2,
            atrPeriod: 14,
          },
        },
        {
          id: "tp-sell",
          type: "take-profit",
          position: { x: 650, y: 540 },
          data: {
            label: "Sell Take Profit",
            category: "trading",
            tradingType: "take-profit",
            method: "RISK_REWARD",
            fixedPips: 100,
            riskRewardRatio: 2,
            atrMultiplier: 3,
            atrPeriod: 14,
          },
        },
      ],
      edges: [
        { id: "e1", source: "timing1", target: "bb1" },
        { id: "e2", source: "timing1", target: "adx1" },
        { id: "e3", source: "bb1", target: "buy1" },
        { id: "e4", source: "bb1", target: "sell1" },
        { id: "e5", source: "adx1", target: "buy1" },
        { id: "e6", source: "adx1", target: "sell1" },
        { id: "e7", source: "buy1", target: "sl-buy" },
        { id: "e8", source: "buy1", target: "tp-buy" },
        { id: "e9", source: "sell1", target: "sl-sell" },
        { id: "e10", source: "sell1", target: "tp-sell" },
      ],
      viewport: { x: 0, y: 0, zoom: 0.8 },
      metadata: meta,
      settings: {
        magicNumber: 100004,
        comment: "BB Squeeze",
        maxOpenTrades: 1,
        allowHedging: false,
        maxTradesPerDay: 0,
      },
    } as BuildJsonSchema,
  },
  {
    id: "macd-trend-following",
    name: "MACD Trend Following",
    description:
      "Trend following strategy using MACD crossover confirmed by ADX trend strength. Trades at all times with a trailing stop to lock in profits.",
    tier: "FREE",
    buildJson: {
      version: "1.0",
      nodes: [
        {
          id: "timing1",
          type: "always",
          position: { x: 300, y: 0 },
          data: {
            label: "Always",
            category: "timing",
            timingType: "always",
          },
        },
        {
          id: "macd1",
          type: "macd",
          position: { x: 100, y: 180 },
          data: {
            label: "MACD (12, 26, 9)",
            category: "indicator",
            indicatorType: "macd",
            timeframe: "H1",
            fastPeriod: 12,
            slowPeriod: 26,
            signalPeriod: 9,
            signalMode: "candle_close",
          },
        },
        {
          id: "adx1",
          type: "adx",
          position: { x: 550, y: 180 },
          data: {
            label: "ADX (14)",
            category: "indicator",
            indicatorType: "adx",
            timeframe: "H1",
            period: 14,
            trendLevel: 20,
            signalMode: "candle_close",
          },
        },
        {
          id: "buy1",
          type: "place-buy",
          position: { x: 100, y: 360 },
          data: {
            label: "Place Buy",
            category: "trading",
            tradingType: "place-buy",
            method: "RISK_PERCENT",
            fixedLot: 0.1,
            riskPercent: 2,
            minLot: 0.01,
            maxLot: 10,
          },
        },
        {
          id: "sell1",
          type: "place-sell",
          position: { x: 550, y: 360 },
          data: {
            label: "Place Sell",
            category: "trading",
            tradingType: "place-sell",
            method: "RISK_PERCENT",
            fixedLot: 0.1,
            riskPercent: 2,
            minLot: 0.01,
            maxLot: 10,
          },
        },
        {
          id: "sl-buy",
          type: "stop-loss",
          position: { x: 0, y: 540 },
          data: {
            label: "Buy Stoploss",
            category: "trading",
            tradingType: "stop-loss",
            method: "ATR_BASED",
            fixedPips: 50,
            atrMultiplier: 2,
            atrPeriod: 14,
          },
        },
        {
          id: "tp-buy",
          type: "take-profit",
          position: { x: 200, y: 540 },
          data: {
            label: "Buy Take Profit",
            category: "trading",
            tradingType: "take-profit",
            method: "RISK_REWARD",
            fixedPips: 100,
            riskRewardRatio: 3,
            atrMultiplier: 3,
            atrPeriod: 14,
          },
        },
        {
          id: "sl-sell",
          type: "stop-loss",
          position: { x: 450, y: 540 },
          data: {
            label: "Sell Stoploss",
            category: "trading",
            tradingType: "stop-loss",
            method: "ATR_BASED",
            fixedPips: 50,
            atrMultiplier: 2,
            atrPeriod: 14,
          },
        },
        {
          id: "tp-sell",
          type: "take-profit",
          position: { x: 650, y: 540 },
          data: {
            label: "Sell Take Profit",
            category: "trading",
            tradingType: "take-profit",
            method: "RISK_REWARD",
            fixedPips: 100,
            riskRewardRatio: 3,
            atrMultiplier: 3,
            atrPeriod: 14,
          },
        },
        {
          id: "trail-buy",
          type: "trailing-stop",
          position: { x: 100, y: 720 },
          data: {
            label: "Buy Trailing Stop",
            category: "trademanagement",
            managementType: "trailing-stop",
            method: "FIXED_PIPS",
            trailPips: 20,
            trailAtrMultiplier: 1,
            trailAtrPeriod: 14,
            trailPercent: 50,
            startAfterPips: 15,
          },
        },
        {
          id: "trail-sell",
          type: "trailing-stop",
          position: { x: 550, y: 720 },
          data: {
            label: "Sell Trailing Stop",
            category: "trademanagement",
            managementType: "trailing-stop",
            method: "FIXED_PIPS",
            trailPips: 20,
            trailAtrMultiplier: 1,
            trailAtrPeriod: 14,
            trailPercent: 50,
            startAfterPips: 15,
          },
        },
      ],
      edges: [
        { id: "e1", source: "timing1", target: "macd1" },
        { id: "e2", source: "timing1", target: "adx1" },
        { id: "e3", source: "macd1", target: "buy1" },
        { id: "e4", source: "macd1", target: "sell1" },
        { id: "e5", source: "adx1", target: "buy1" },
        { id: "e6", source: "adx1", target: "sell1" },
        { id: "e7", source: "buy1", target: "sl-buy" },
        { id: "e8", source: "buy1", target: "tp-buy" },
        { id: "e9", source: "sell1", target: "sl-sell" },
        { id: "e10", source: "sell1", target: "tp-sell" },
        { id: "e11", source: "buy1", target: "trail-buy" },
        { id: "e12", source: "sell1", target: "trail-sell" },
      ],
      viewport: { x: 0, y: 0, zoom: 0.8 },
      metadata: meta,
      settings: {
        magicNumber: 100005,
        comment: "MACD Trend Following",
        maxOpenTrades: 1,
        allowHedging: false,
        maxTradesPerDay: 0,
      },
    } as BuildJsonSchema,
  },
  {
    id: "stochastic-reversal",
    name: "Stochastic Reversal",
    description:
      "Reversal strategy using Stochastic oscillator at support and resistance levels during the Tokyo session. Buys at oversold levels near support, sells at overbought levels near resistance.",
    tier: "FREE",
    buildJson: {
      version: "1.0",
      nodes: [
        {
          id: "timing1",
          type: "trading-session",
          position: { x: 300, y: 0 },
          data: {
            label: "Tokyo Session",
            category: "timing",
            timingType: "trading-session",
            session: "TOKYO",
            tradeMondayToFriday: true,
          },
        },
        {
          id: "stoch1",
          type: "stochastic",
          position: { x: 100, y: 180 },
          data: {
            label: "Stochastic (14, 3, 3)",
            category: "indicator",
            indicatorType: "stochastic",
            timeframe: "M15",
            kPeriod: 14,
            dPeriod: 3,
            slowing: 3,
            overboughtLevel: 80,
            oversoldLevel: 20,
            signalMode: "candle_close",
          },
        },
        {
          id: "sr1",
          type: "support-resistance",
          position: { x: 550, y: 180 },
          data: {
            label: "Support/Resistance",
            category: "priceaction",
            priceActionType: "support-resistance",
            timeframe: "H1",
            lookbackPeriod: 100,
            touchCount: 2,
            zoneSize: 10,
          },
        },
        {
          id: "buy1",
          type: "place-buy",
          position: { x: 100, y: 360 },
          data: {
            label: "Place Buy",
            category: "trading",
            tradingType: "place-buy",
            method: "RISK_PERCENT",
            fixedLot: 0.1,
            riskPercent: 1,
            minLot: 0.01,
            maxLot: 10,
          },
        },
        {
          id: "sell1",
          type: "place-sell",
          position: { x: 550, y: 360 },
          data: {
            label: "Place Sell",
            category: "trading",
            tradingType: "place-sell",
            method: "RISK_PERCENT",
            fixedLot: 0.1,
            riskPercent: 1,
            minLot: 0.01,
            maxLot: 10,
          },
        },
        {
          id: "sl-buy",
          type: "stop-loss",
          position: { x: 0, y: 540 },
          data: {
            label: "Buy Stoploss",
            category: "trading",
            tradingType: "stop-loss",
            method: "FIXED_PIPS",
            fixedPips: 25,
            atrMultiplier: 1.5,
            atrPeriod: 14,
          },
        },
        {
          id: "tp-buy",
          type: "take-profit",
          position: { x: 200, y: 540 },
          data: {
            label: "Buy Take Profit",
            category: "trading",
            tradingType: "take-profit",
            method: "FIXED_PIPS",
            fixedPips: 50,
            riskRewardRatio: 2,
            atrMultiplier: 3,
            atrPeriod: 14,
          },
        },
        {
          id: "sl-sell",
          type: "stop-loss",
          position: { x: 450, y: 540 },
          data: {
            label: "Sell Stoploss",
            category: "trading",
            tradingType: "stop-loss",
            method: "FIXED_PIPS",
            fixedPips: 25,
            atrMultiplier: 1.5,
            atrPeriod: 14,
          },
        },
        {
          id: "tp-sell",
          type: "take-profit",
          position: { x: 650, y: 540 },
          data: {
            label: "Sell Take Profit",
            category: "trading",
            tradingType: "take-profit",
            method: "FIXED_PIPS",
            fixedPips: 50,
            riskRewardRatio: 2,
            atrMultiplier: 3,
            atrPeriod: 14,
          },
        },
      ],
      edges: [
        { id: "e1", source: "timing1", target: "stoch1" },
        { id: "e2", source: "timing1", target: "sr1" },
        { id: "e3", source: "stoch1", target: "buy1" },
        { id: "e4", source: "stoch1", target: "sell1" },
        { id: "e5", source: "sr1", target: "buy1" },
        { id: "e6", source: "sr1", target: "sell1" },
        { id: "e7", source: "buy1", target: "sl-buy" },
        { id: "e8", source: "buy1", target: "tp-buy" },
        { id: "e9", source: "sell1", target: "sl-sell" },
        { id: "e10", source: "sell1", target: "tp-sell" },
      ],
      viewport: { x: 0, y: 0, zoom: 0.8 },
      metadata: meta,
      settings: {
        magicNumber: 100006,
        comment: "Stochastic Reversal",
        maxOpenTrades: 1,
        allowHedging: false,
        maxTradesPerDay: 0,
      },
    } as BuildJsonSchema,
  },
  {
    id: "london-breakout",
    name: "London Breakout",
    description:
      "Range breakout strategy targeting the London session open. Trades breakouts of the Asian session range with ATR volatility filter during custom hours (8:00-17:00).",
    tier: "FREE",
    buildJson: {
      version: "1.0",
      nodes: [
        {
          id: "timing1",
          type: "custom-times",
          position: { x: 300, y: 0 },
          data: {
            label: "London Hours",
            category: "timing",
            timingType: "custom-times",
            days: {
              monday: true,
              tuesday: true,
              wednesday: true,
              thursday: true,
              friday: true,
              saturday: false,
              sunday: false,
            },
            timeSlots: [{ startHour: 8, startMinute: 0, endHour: 17, endMinute: 0 }],
          },
        },
        {
          id: "rb1",
          type: "range-breakout",
          position: { x: 100, y: 180 },
          data: {
            label: "Asian Range Breakout",
            category: "priceaction",
            priceActionType: "range-breakout",
            timeframe: "M15",
            rangeType: "SESSION",
            lookbackCandles: 20,
            rangeSession: "ASIAN",
            sessionStartHour: 0,
            sessionStartMinute: 0,
            sessionEndHour: 8,
            sessionEndMinute: 0,
            breakoutDirection: "BOTH",
            entryMode: "ON_CLOSE",
            bufferPips: 3,
            minRangePips: 15,
            maxRangePips: 60,
          },
        },
        {
          id: "atr1",
          type: "atr",
          position: { x: 550, y: 180 },
          data: {
            label: "ATR Filter (14)",
            category: "indicator",
            indicatorType: "atr",
            timeframe: "H1",
            period: 14,
            signalMode: "candle_close",
          },
        },
        {
          id: "buy1",
          type: "place-buy",
          position: { x: 100, y: 360 },
          data: {
            label: "Place Buy",
            category: "trading",
            tradingType: "place-buy",
            method: "RISK_PERCENT",
            fixedLot: 0.1,
            riskPercent: 2,
            minLot: 0.01,
            maxLot: 10,
          },
        },
        {
          id: "sell1",
          type: "place-sell",
          position: { x: 550, y: 360 },
          data: {
            label: "Place Sell",
            category: "trading",
            tradingType: "place-sell",
            method: "RISK_PERCENT",
            fixedLot: 0.1,
            riskPercent: 2,
            minLot: 0.01,
            maxLot: 10,
          },
        },
        {
          id: "sl-buy",
          type: "stop-loss",
          position: { x: 0, y: 540 },
          data: {
            label: "Buy ATR Stoploss",
            category: "trading",
            tradingType: "stop-loss",
            method: "ATR_BASED",
            fixedPips: 50,
            atrMultiplier: 1.5,
            atrPeriod: 14,
          },
        },
        {
          id: "tp-buy",
          type: "take-profit",
          position: { x: 200, y: 540 },
          data: {
            label: "Buy Take Profit",
            category: "trading",
            tradingType: "take-profit",
            method: "RISK_REWARD",
            fixedPips: 100,
            riskRewardRatio: 2,
            atrMultiplier: 3,
            atrPeriod: 14,
          },
        },
        {
          id: "sl-sell",
          type: "stop-loss",
          position: { x: 450, y: 540 },
          data: {
            label: "Sell ATR Stoploss",
            category: "trading",
            tradingType: "stop-loss",
            method: "ATR_BASED",
            fixedPips: 50,
            atrMultiplier: 1.5,
            atrPeriod: 14,
          },
        },
        {
          id: "tp-sell",
          type: "take-profit",
          position: { x: 650, y: 540 },
          data: {
            label: "Sell Take Profit",
            category: "trading",
            tradingType: "take-profit",
            method: "RISK_REWARD",
            fixedPips: 100,
            riskRewardRatio: 2,
            atrMultiplier: 3,
            atrPeriod: 14,
          },
        },
      ],
      edges: [
        { id: "e1", source: "timing1", target: "rb1" },
        { id: "e2", source: "timing1", target: "atr1" },
        { id: "e3", source: "rb1", target: "buy1" },
        { id: "e4", source: "rb1", target: "sell1" },
        { id: "e5", source: "atr1", target: "buy1" },
        { id: "e6", source: "atr1", target: "sell1" },
        { id: "e7", source: "buy1", target: "sl-buy" },
        { id: "e8", source: "buy1", target: "tp-buy" },
        { id: "e9", source: "sell1", target: "sl-sell" },
        { id: "e10", source: "sell1", target: "tp-sell" },
      ],
      viewport: { x: 0, y: 0, zoom: 0.8 },
      metadata: meta,
      settings: {
        magicNumber: 100007,
        comment: "London Breakout",
        maxOpenTrades: 1,
        allowHedging: false,
        maxTradesPerDay: 0,
      },
    } as BuildJsonSchema,
  },
  {
    id: "multi-ma-trend",
    name: "Multi-MA Trend",
    description:
      "Triple moving average alignment strategy using fast (10), medium (25), and slow (50) EMAs. Buys when all three align bullish, sells when all three align bearish.",
    tier: "FREE",
    buildJson: {
      version: "1.0",
      nodes: [
        {
          id: "timing1",
          type: "always",
          position: { x: 300, y: 0 },
          data: {
            label: "Always",
            category: "timing",
            timingType: "always",
          },
        },
        {
          id: "ma-fast",
          type: "moving-average",
          position: { x: 0, y: 180 },
          data: {
            label: "Fast MA (10)",
            category: "indicator",
            indicatorType: "moving-average",
            timeframe: "H1",
            period: 10,
            method: "EMA",
            signalMode: "candle_close",
            shift: 0,
          },
        },
        {
          id: "ma-medium",
          type: "moving-average",
          position: { x: 300, y: 180 },
          data: {
            label: "Medium MA (25)",
            category: "indicator",
            indicatorType: "moving-average",
            timeframe: "H1",
            period: 25,
            method: "EMA",
            signalMode: "candle_close",
            shift: 0,
          },
        },
        {
          id: "ma-slow",
          type: "moving-average",
          position: { x: 600, y: 180 },
          data: {
            label: "Slow MA (50)",
            category: "indicator",
            indicatorType: "moving-average",
            timeframe: "H1",
            period: 50,
            method: "EMA",
            signalMode: "candle_close",
            shift: 0,
          },
        },
        {
          id: "buy1",
          type: "place-buy",
          position: { x: 100, y: 360 },
          data: {
            label: "Place Buy",
            category: "trading",
            tradingType: "place-buy",
            method: "RISK_PERCENT",
            fixedLot: 0.1,
            riskPercent: 2,
            minLot: 0.01,
            maxLot: 10,
          },
        },
        {
          id: "sell1",
          type: "place-sell",
          position: { x: 550, y: 360 },
          data: {
            label: "Place Sell",
            category: "trading",
            tradingType: "place-sell",
            method: "RISK_PERCENT",
            fixedLot: 0.1,
            riskPercent: 2,
            minLot: 0.01,
            maxLot: 10,
          },
        },
        {
          id: "sl-buy",
          type: "stop-loss",
          position: { x: 0, y: 540 },
          data: {
            label: "Buy Stoploss",
            category: "trading",
            tradingType: "stop-loss",
            method: "ATR_BASED",
            fixedPips: 50,
            atrMultiplier: 2,
            atrPeriod: 14,
          },
        },
        {
          id: "tp-buy",
          type: "take-profit",
          position: { x: 200, y: 540 },
          data: {
            label: "Buy Take Profit",
            category: "trading",
            tradingType: "take-profit",
            method: "RISK_REWARD",
            fixedPips: 100,
            riskRewardRatio: 2.5,
            atrMultiplier: 3,
            atrPeriod: 14,
          },
        },
        {
          id: "sl-sell",
          type: "stop-loss",
          position: { x: 450, y: 540 },
          data: {
            label: "Sell Stoploss",
            category: "trading",
            tradingType: "stop-loss",
            method: "ATR_BASED",
            fixedPips: 50,
            atrMultiplier: 2,
            atrPeriod: 14,
          },
        },
        {
          id: "tp-sell",
          type: "take-profit",
          position: { x: 650, y: 540 },
          data: {
            label: "Sell Take Profit",
            category: "trading",
            tradingType: "take-profit",
            method: "RISK_REWARD",
            fixedPips: 100,
            riskRewardRatio: 2.5,
            atrMultiplier: 3,
            atrPeriod: 14,
          },
        },
      ],
      edges: [
        { id: "e1", source: "timing1", target: "ma-fast" },
        { id: "e2", source: "timing1", target: "ma-medium" },
        { id: "e3", source: "timing1", target: "ma-slow" },
        { id: "e4", source: "ma-fast", target: "buy1" },
        { id: "e5", source: "ma-medium", target: "buy1" },
        { id: "e6", source: "ma-slow", target: "buy1" },
        { id: "e7", source: "ma-fast", target: "sell1" },
        { id: "e8", source: "ma-medium", target: "sell1" },
        { id: "e9", source: "ma-slow", target: "sell1" },
        { id: "e10", source: "buy1", target: "sl-buy" },
        { id: "e11", source: "buy1", target: "tp-buy" },
        { id: "e12", source: "sell1", target: "sl-sell" },
        { id: "e13", source: "sell1", target: "tp-sell" },
      ],
      viewport: { x: 0, y: 0, zoom: 0.8 },
      metadata: meta,
      settings: {
        magicNumber: 100008,
        comment: "Multi-MA Trend",
        maxOpenTrades: 1,
        allowHedging: false,
        maxTradesPerDay: 0,
      },
    } as BuildJsonSchema,
  },
  {
    id: "rsi-bb-mean-reversion",
    name: "RSI + BB Mean Reversion",
    description:
      "Mean reversion strategy combining RSI oversold/overbought signals with Bollinger Band touches during the London session. Buys when RSI is oversold and price touches the lower band.",
    tier: "FREE",
    buildJson: {
      version: "1.0",
      nodes: [
        {
          id: "timing1",
          type: "trading-session",
          position: { x: 300, y: 0 },
          data: {
            label: "London Session",
            category: "timing",
            timingType: "trading-session",
            session: "LONDON",
            tradeMondayToFriday: true,
          },
        },
        {
          id: "rsi1",
          type: "rsi",
          position: { x: 100, y: 180 },
          data: {
            label: "RSI (14)",
            category: "indicator",
            indicatorType: "rsi",
            timeframe: "M15",
            period: 14,
            signalMode: "candle_close",
            overboughtLevel: 70,
            oversoldLevel: 30,
          },
        },
        {
          id: "bb1",
          type: "bollinger-bands",
          position: { x: 550, y: 180 },
          data: {
            label: "Bollinger Bands (20, 2)",
            category: "indicator",
            indicatorType: "bollinger-bands",
            timeframe: "M15",
            period: 20,
            deviation: 2,
            shift: 0,
            signalMode: "candle_close",
          },
        },
        {
          id: "buy1",
          type: "place-buy",
          position: { x: 100, y: 360 },
          data: {
            label: "Place Buy",
            category: "trading",
            tradingType: "place-buy",
            method: "RISK_PERCENT",
            fixedLot: 0.1,
            riskPercent: 1.5,
            minLot: 0.01,
            maxLot: 10,
          },
        },
        {
          id: "sell1",
          type: "place-sell",
          position: { x: 550, y: 360 },
          data: {
            label: "Place Sell",
            category: "trading",
            tradingType: "place-sell",
            method: "RISK_PERCENT",
            fixedLot: 0.1,
            riskPercent: 1.5,
            minLot: 0.01,
            maxLot: 10,
          },
        },
        {
          id: "sl-buy",
          type: "stop-loss",
          position: { x: 0, y: 540 },
          data: {
            label: "Buy Stoploss",
            category: "trading",
            tradingType: "stop-loss",
            method: "FIXED_PIPS",
            fixedPips: 30,
            atrMultiplier: 1.5,
            atrPeriod: 14,
          },
        },
        {
          id: "tp-buy",
          type: "take-profit",
          position: { x: 200, y: 540 },
          data: {
            label: "Buy Take Profit",
            category: "trading",
            tradingType: "take-profit",
            method: "RISK_REWARD",
            fixedPips: 100,
            riskRewardRatio: 2,
            atrMultiplier: 3,
            atrPeriod: 14,
          },
        },
        {
          id: "sl-sell",
          type: "stop-loss",
          position: { x: 450, y: 540 },
          data: {
            label: "Sell Stoploss",
            category: "trading",
            tradingType: "stop-loss",
            method: "FIXED_PIPS",
            fixedPips: 30,
            atrMultiplier: 1.5,
            atrPeriod: 14,
          },
        },
        {
          id: "tp-sell",
          type: "take-profit",
          position: { x: 650, y: 540 },
          data: {
            label: "Sell Take Profit",
            category: "trading",
            tradingType: "take-profit",
            method: "RISK_REWARD",
            fixedPips: 100,
            riskRewardRatio: 2,
            atrMultiplier: 3,
            atrPeriod: 14,
          },
        },
      ],
      edges: [
        { id: "e1", source: "timing1", target: "rsi1" },
        { id: "e2", source: "timing1", target: "bb1" },
        { id: "e3", source: "rsi1", target: "buy1" },
        { id: "e4", source: "rsi1", target: "sell1" },
        { id: "e5", source: "bb1", target: "buy1" },
        { id: "e6", source: "bb1", target: "sell1" },
        { id: "e7", source: "buy1", target: "sl-buy" },
        { id: "e8", source: "buy1", target: "tp-buy" },
        { id: "e9", source: "sell1", target: "sl-sell" },
        { id: "e10", source: "sell1", target: "tp-sell" },
      ],
      viewport: { x: 0, y: 0, zoom: 0.8 },
      metadata: meta,
      settings: {
        magicNumber: 100009,
        comment: "RSI + BB Mean Reversion",
        maxOpenTrades: 1,
        allowHedging: false,
        maxTradesPerDay: 0,
      },
    } as BuildJsonSchema,
  },
  {
    id: "cci-momentum",
    name: "CCI Momentum",
    description:
      "Momentum strategy using CCI crossover with ATR-based stop loss during custom trading hours (9:00-20:00). Buys when CCI crosses above -100, sells when CCI crosses below 100.",
    tier: "FREE",
    buildJson: {
      version: "1.0",
      nodes: [
        {
          id: "timing1",
          type: "custom-times",
          position: { x: 300, y: 0 },
          data: {
            label: "Trading Hours",
            category: "timing",
            timingType: "custom-times",
            days: {
              monday: true,
              tuesday: true,
              wednesday: true,
              thursday: true,
              friday: true,
              saturday: false,
              sunday: false,
            },
            timeSlots: [{ startHour: 9, startMinute: 0, endHour: 20, endMinute: 0 }],
          },
        },
        {
          id: "cci1",
          type: "cci",
          position: { x: 300, y: 180 },
          data: {
            label: "CCI (20)",
            category: "indicator",
            indicatorType: "cci",
            timeframe: "H1",
            period: 20,
            overboughtLevel: 100,
            oversoldLevel: -100,
            signalMode: "candle_close",
          },
        },
        {
          id: "buy1",
          type: "place-buy",
          position: { x: 100, y: 360 },
          data: {
            label: "Place Buy",
            category: "trading",
            tradingType: "place-buy",
            method: "RISK_PERCENT",
            fixedLot: 0.1,
            riskPercent: 2,
            minLot: 0.01,
            maxLot: 10,
          },
        },
        {
          id: "sell1",
          type: "place-sell",
          position: { x: 550, y: 360 },
          data: {
            label: "Place Sell",
            category: "trading",
            tradingType: "place-sell",
            method: "RISK_PERCENT",
            fixedLot: 0.1,
            riskPercent: 2,
            minLot: 0.01,
            maxLot: 10,
          },
        },
        {
          id: "sl-buy",
          type: "stop-loss",
          position: { x: 0, y: 540 },
          data: {
            label: "Buy ATR Stoploss",
            category: "trading",
            tradingType: "stop-loss",
            method: "ATR_BASED",
            fixedPips: 50,
            atrMultiplier: 1.5,
            atrPeriod: 14,
          },
        },
        {
          id: "tp-buy",
          type: "take-profit",
          position: { x: 200, y: 540 },
          data: {
            label: "Buy Take Profit",
            category: "trading",
            tradingType: "take-profit",
            method: "RISK_REWARD",
            fixedPips: 100,
            riskRewardRatio: 2,
            atrMultiplier: 3,
            atrPeriod: 14,
          },
        },
        {
          id: "sl-sell",
          type: "stop-loss",
          position: { x: 450, y: 540 },
          data: {
            label: "Sell ATR Stoploss",
            category: "trading",
            tradingType: "stop-loss",
            method: "ATR_BASED",
            fixedPips: 50,
            atrMultiplier: 1.5,
            atrPeriod: 14,
          },
        },
        {
          id: "tp-sell",
          type: "take-profit",
          position: { x: 650, y: 540 },
          data: {
            label: "Sell Take Profit",
            category: "trading",
            tradingType: "take-profit",
            method: "RISK_REWARD",
            fixedPips: 100,
            riskRewardRatio: 2,
            atrMultiplier: 3,
            atrPeriod: 14,
          },
        },
      ],
      edges: [
        { id: "e1", source: "timing1", target: "cci1" },
        { id: "e2", source: "cci1", target: "buy1" },
        { id: "e3", source: "cci1", target: "sell1" },
        { id: "e4", source: "buy1", target: "sl-buy" },
        { id: "e5", source: "buy1", target: "tp-buy" },
        { id: "e6", source: "sell1", target: "sl-sell" },
        { id: "e7", source: "sell1", target: "tp-sell" },
      ],
      viewport: { x: 0, y: 0, zoom: 0.8 },
      metadata: meta,
      settings: {
        magicNumber: 100010,
        comment: "CCI Momentum",
        maxOpenTrades: 1,
        allowHedging: false,
        maxTradesPerDay: 0,
      },
    } as BuildJsonSchema,
  },
];
