export const VERIFICATION = {
  MIN_TRADE_COUNT: 30,
  MONTE_CARLO_ITERATIONS: 10_000,
  MAX_SHARPE_DEGRADATION_PCT: 40,
  EXTREME_SHARPE_DEGRADATION_PCT: 80,
  MIN_OOS_TRADE_COUNT: 20,
  READY_CONFIDENCE_THRESHOLD: 0.75,
  NOT_DEPLOYABLE_THRESHOLD: 0.45,
  RUIN_PROBABILITY_CEILING: 0.15,
  CONFIG_VERSION: "1.0.0",
} as const;
