export const VERIFICATION = {
  MIN_TRADE_COUNT: 30,
  MONTE_CARLO_ITERATIONS: 10_000,
  READY_CONFIDENCE_THRESHOLD: 0.75,
  NOT_DEPLOYABLE_THRESHOLD: 0.45,
  RUIN_PROBABILITY_CEILING: 0.15,
  CONFIG_VERSION: "3.0.0",
} as const;
