// MQL5 Code Templates

import type { GeneratorContext, OptimizableInput } from "./types";
import { sanitizeMQL5String } from "./generators/shared";

export function generateFileHeader(ctx: GeneratorContext): string {
  const timestamp = new Date().toISOString();
  const desc = ctx.description ? sanitizeMQL5String(ctx.description) : "";
  // Sanitize project name for comment lines (strip characters that could break MQL comment syntax)
  const safeName = ctx.projectName.replace(/[^\w\s\-.]/g, "").substring(0, 36);
  // MQL5 #property description lines (max 511 chars each, split on newlines)
  const descLines = desc
    ? desc
        .split(/\\n|\n/)
        .filter((l: string) => l.trim())
        .map((l: string) => `#property description "${l.substring(0, 511)}"`)
        .join("\n")
    : `#property description "${safeName} — Generated by AlgoStudio"`;
  return `//+------------------------------------------------------------------+
//|                                    ${safeName.padEnd(36)}|
//|                                    Generated by AlgoStudio        |
//|                                    ${timestamp.substring(0, 19).padEnd(36)}|
//+------------------------------------------------------------------+
#property copyright "AlgoStudio"
#property link      "https://algo-studio.com"
#property version   "1.00"
${descLines}

`;
}

export function generateTradeIncludes(): string {
  return `//--- Include trade library
#include <Trade\\Trade.mqh>

//--- Trade object
CTrade trade;

`;
}

export function generateInputsSection(inputs: OptimizableInput[]): string {
  if (inputs.length === 0) return "";

  const lines: string[] = [];
  let currentGroup = "";

  // Emit custom timeframe enum if any timeframe inputs exist
  const hasTimeframeInputs = inputs.some((i) => i.type === "ENUM_AS_TIMEFRAMES");
  if (hasTimeframeInputs) {
    lines.push("//--- Timeframes (only AlgoStudio-supported timeframes for optimization)");
    lines.push("enum ENUM_AS_TIMEFRAMES");
    lines.push("{");
    lines.push("   TF_M1  = PERIOD_M1,   // M1");
    lines.push("   TF_M5  = PERIOD_M5,   // M5");
    lines.push("   TF_M15 = PERIOD_M15,  // M15");
    lines.push("   TF_M30 = PERIOD_M30,  // M30");
    lines.push("   TF_H1  = PERIOD_H1,   // H1");
    lines.push("   TF_H4  = PERIOD_H4,   // H4");
    lines.push("   TF_D1  = PERIOD_D1,   // D1");
    lines.push("   TF_W1  = PERIOD_W1,   // W1");
    lines.push("   TF_MN1 = PERIOD_MN1   // MN1");
    lines.push("};");
    lines.push("");
  }

  for (const input of inputs) {
    // Add group header when group changes
    if (input.group && input.group !== currentGroup) {
      currentGroup = input.group;
      if (lines.length > 0) lines.push("");
      lines.push(`//--- ${currentGroup}`);
    }

    // Wrap string-type values in double quotes for valid MQL5 syntax
    const formattedValue = input.type === "string" ? `"${input.value}"` : input.value;

    if (input.isOptimizable) {
      // Optimizable: visible in MT5 Input Parameters and included in optimization
      lines.push(`input ${input.type} ${input.name} = ${formattedValue}; // ${input.comment}`);
    } else if (input.alwaysVisible) {
      // Core/filter settings: visible in MT5 Input Parameters but NOT optimizable
      lines.push(`sinput ${input.type} ${input.name} = ${formattedValue}; // ${input.comment}`);
    } else {
      // Node parameters with optimize unchecked: constant, hidden from MT5 Input tab
      lines.push(`const ${input.type} ${input.name} = ${formattedValue}; // ${input.comment}`);
    }
  }

  return `//+------------------------------------------------------------------+
//| Input Parameters                                                   |
//+------------------------------------------------------------------+
${lines.join("\n")}

`;
}

export function generateGlobalVariablesSection(variables: string[]): string {
  if (variables.length === 0) return "";

  return `//+------------------------------------------------------------------+
//| Global Variables                                                   |
//+------------------------------------------------------------------+
${variables.join("\n")}

`;
}

export function generateOnInit(ctx: GeneratorContext, initCode: string[]): string {
  return `//+------------------------------------------------------------------+
//| Expert initialization function                                     |
//+------------------------------------------------------------------+
int OnInit()
{
   //--- Validate symbol allows full trading
   if(SymbolInfoInteger(_Symbol, SYMBOL_TRADE_MODE) != SYMBOL_TRADE_MODE_FULL)
   {
      Print("Symbol ", _Symbol, " does not allow full trading (mode: ",
            EnumToString((ENUM_SYMBOL_TRADE_MODE)SymbolInfoInteger(_Symbol, SYMBOL_TRADE_MODE)), ")");
      return(INIT_FAILED);
   }

   //--- Set magic number for trade operations
   trade.SetExpertMagicNumber(InpMagicNumber);

   //--- Set allowed slippage
   trade.SetDeviationInPoints(InpMaxSlippage);

   //--- Set trade fill type
   trade.SetTypeFillingBySymbol(_Symbol);

${initCode.map((line) => "   " + line).join("\n")}

   //--- Display strategy info on chart
   ShowStrategyOverlay();

   Print("${ctx.projectName} initialized successfully on ", _Symbol, " ", EnumToString(Period()));
   return(INIT_SUCCEEDED);
}

`;
}

export function generateOnDeinit(deinitCode: string[]): string {
  return `//+------------------------------------------------------------------+
//| Expert deinitialization function                                   |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   //--- Release indicator handles
${deinitCode.length > 0 ? deinitCode.map((line) => "   " + line).join("\n") : "   //--- No handles to release"}

   //--- Remove strategy overlay from chart
   ObjectsDeleteAll(0, "AS_Info_");
   Comment("");

   //--- Log deinitialization reason
   string reasonText;
   switch(reason)
   {
      case REASON_PROGRAM:     reasonText = "EA stopped by user"; break;
      case REASON_REMOVE:      reasonText = "EA removed from chart"; break;
      case REASON_RECOMPILE:   reasonText = "EA recompiled"; break;
      case REASON_CHARTCHANGE: reasonText = "Symbol or timeframe changed"; break;
      case REASON_CHARTCLOSE:  reasonText = "Chart closed"; break;
      case REASON_PARAMETERS:  reasonText = "Input parameters changed"; break;
      case REASON_ACCOUNT:     reasonText = "Account changed"; break;
      case REASON_TEMPLATE:    reasonText = "Template applied"; break;
      default:                 reasonText = "Unknown reason (" + IntegerToString(reason) + ")"; break;
   }
   Print("EA deinitialized: ", reasonText);
}

`;
}

export function generateOnTick(
  ctx: GeneratorContext,
  tickCode: string[],
  maxIndicatorPeriod: number = 0
): string {
  // Build daily P&L check code if enabled
  let dailyPnlCode = "";
  if (ctx.maxDailyProfitPercent > 0 || ctx.maxDailyLossPercent > 0) {
    dailyPnlCode = `
   //--- Daily P&L Protection
   {
      double dailyPnL = 0;
      datetime todayStart = iTime(_Symbol, PERIOD_D1, 0);

      // Sum closed trades today
      HistorySelect(todayStart, TimeCurrent());
      for(int i = HistoryDealsTotal() - 1; i >= 0; i--)
      {
         ulong dealTicket = HistoryDealGetTicket(i);
         if(dealTicket > 0 && HistoryDealGetInteger(dealTicket, DEAL_MAGIC) == InpMagicNumber
            && HistoryDealGetString(dealTicket, DEAL_SYMBOL) == _Symbol
            && HistoryDealGetInteger(dealTicket, DEAL_ENTRY) == DEAL_ENTRY_OUT)
         {
            dailyPnL += HistoryDealGetDouble(dealTicket, DEAL_PROFIT)
                      + HistoryDealGetDouble(dealTicket, DEAL_SWAP)
                      + HistoryDealGetDouble(dealTicket, DEAL_COMMISSION);
         }
      }

      // Add floating P&L
      for(int i = PositionsTotal() - 1; i >= 0; i--)
      {
         ulong ticket = PositionGetTicket(i);
         if(ticket > 0 && PositionGetInteger(POSITION_MAGIC) == InpMagicNumber
            && PositionGetString(POSITION_SYMBOL) == _Symbol)
            dailyPnL += PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);
      }

      double balance = AccountInfoDouble(ACCOUNT_BALANCE);
      double dailyPnLPercent = (balance > 0) ? (dailyPnL / balance) * 100.0 : 0;

      // Reset daily limit flags on new day
      static datetime lastPnLDay = 0;
      static bool profitLimitHit = false;
      static bool lossLimitHit = false;
      if(todayStart != lastPnLDay)
      {
         lastPnLDay = todayStart;
         profitLimitHit = false;
         lossLimitHit = false;
      }
      if(profitLimitHit || lossLimitHit) return;
`;
    if (ctx.maxDailyProfitPercent > 0) {
      dailyPnlCode += `
      if(dailyPnLPercent >= ${ctx.maxDailyProfitPercent})
      {
         CloseAllPositions();
         Print("Daily profit target reached: ", DoubleToString(dailyPnLPercent, 2), "%");
         profitLimitHit = true;
         return;
      }
`;
    }
    if (ctx.maxDailyLossPercent > 0) {
      dailyPnlCode += `
      if(dailyPnLPercent <= -${ctx.maxDailyLossPercent})
      {
         CloseAllPositions();
         Print("Daily loss limit reached: ", DoubleToString(dailyPnLPercent, 2), "%");
         lossLimitHit = true;
         return;
      }
`;
    }
    dailyPnlCode += "   }\n";
  }

  // Build total drawdown check if enabled
  let totalDrawdownCode = "";
  if (ctx.maxTotalDrawdownPercent > 0) {
    totalDrawdownCode = `
   //--- Total Drawdown Protection
   {
      static double gPeakEquity = 0;
      double equity = AccountInfoDouble(ACCOUNT_EQUITY);
      if(equity > gPeakEquity) gPeakEquity = equity;
      if(gPeakEquity > 0)
      {
         double dd = (gPeakEquity - equity) / gPeakEquity * 100.0;
         if(dd >= ${ctx.maxTotalDrawdownPercent})
         {
            CloseAllPositions();
            Print("Total drawdown limit reached: ", DoubleToString(dd, 2), "% (max ${ctx.maxTotalDrawdownPercent}%)");
            return;
         }
      }
   }
`;
  }

  // Build equity target check if enabled
  let equityTargetCode = "";
  if (ctx.equityTargetPercent > 0) {
    equityTargetCode = `
   //--- Equity Target
   {
      static double gStartBalance = 0;
      if(gStartBalance == 0) gStartBalance = AccountInfoDouble(ACCOUNT_BALANCE);
      double equity = AccountInfoDouble(ACCOUNT_EQUITY);
      double growth = (equity - gStartBalance) / gStartBalance * 100.0;
      if(growth >= ${ctx.equityTargetPercent})
      {
         CloseAllPositions();
         Print("Equity target reached: +", DoubleToString(growth, 2), "% (target ${ctx.equityTargetPercent}%)");
         return;
      }
   }
`;
  }

  // Build cooldown after loss check if enabled
  let cooldownCode = "";
  if (ctx.cooldownAfterLossMinutes > 0) {
    cooldownCode = `
   //--- Cooldown After Loss
   {
      static datetime gLastLossTime = 0;
      datetime todayStart = iTime(_Symbol, PERIOD_D1, 0);
      HistorySelect(todayStart, TimeCurrent());
      for(int d = HistoryDealsTotal() - 1; d >= 0; d--)
      {
         ulong dealTicket = HistoryDealGetTicket(d);
         if(dealTicket > 0 && HistoryDealGetInteger(dealTicket, DEAL_MAGIC) == InpMagicNumber
            && HistoryDealGetString(dealTicket, DEAL_SYMBOL) == _Symbol
            && HistoryDealGetInteger(dealTicket, DEAL_ENTRY) == DEAL_ENTRY_OUT)
         {
            double dealProfit = HistoryDealGetDouble(dealTicket, DEAL_PROFIT)
                              + HistoryDealGetDouble(dealTicket, DEAL_SWAP)
                              + HistoryDealGetDouble(dealTicket, DEAL_COMMISSION);
            if(dealProfit < 0)
            {
               datetime dealTime = (datetime)HistoryDealGetInteger(dealTicket, DEAL_TIME);
               if(dealTime > gLastLossTime) gLastLossTime = dealTime;
               break; // Found the most recent loss — no need to keep searching
            }
         }
      }
      if(gLastLossTime > 0 && TimeCurrent() - gLastLossTime < ${ctx.cooldownAfterLossMinutes} * 60)
         return;
   }
`;
  }

  // Build min bars between trades check if enabled
  let minBarsCode = "";
  if (ctx.minBarsBetweenTrades > 0) {
    minBarsCode = `
   //--- Min Bars Between Trades
   static int gLastTradeBar = 0;
   {
      int currentBar = iBars(_Symbol, PERIOD_CURRENT);
      if(gLastTradeBar > 0 && currentBar - gLastTradeBar < ${ctx.minBarsBetweenTrades})
         return;
   }
`;
  }

  return `//+------------------------------------------------------------------+
//| Expert tick function                                               |
//+------------------------------------------------------------------+
void OnTick()
{
   //--- Check if trading is allowed
   if(!TerminalInfoInteger(TERMINAL_TRADE_ALLOWED)) return;
   if(!MQLInfoInteger(MQL_TRADE_ALLOWED)) return;

   //--- Check for new bar (optional: only trade on new bars)
   static datetime lastBarTime = 0;
   datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   bool isNewBar = (currentBarTime != lastBarTime);
   if(isNewBar) lastBarTime = currentBarTime;

   //--- Check minimum bars available
   if(Bars(_Symbol, PERIOD_CURRENT) < ${Math.max(maxIndicatorPeriod * 3, 100)})
   {
      static bool barsWarned = false;
      if(!barsWarned) { Print("Waiting for minimum bars (${Math.max(maxIndicatorPeriod * 3, 100)}) on ", _Symbol); barsWarned = true; }
      return;
   }

${totalDrawdownCode}${equityTargetCode}${dailyPnlCode}${cooldownCode}${minBarsCode}
   //--- Count current positions
   int positionsCount = CountPositions();

${tickCode.map((line) => "   " + line).join("\n")}
}

`;
}

export function generateHelperFunctions(_ctx: GeneratorContext): string {
  return `//+------------------------------------------------------------------+
//| Count positions for this EA                                        |
//+------------------------------------------------------------------+
int CountPositions()
{
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
      {
         if(PositionGetInteger(POSITION_MAGIC) == InpMagicNumber &&
            PositionGetString(POSITION_SYMBOL) == _Symbol)
         {
            count++;
         }
      }
   }
   return count;
}

//+------------------------------------------------------------------+
//| Count positions by type                                            |
//+------------------------------------------------------------------+
int CountPositionsByType(ENUM_POSITION_TYPE posType)
{
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
      {
         if(PositionGetInteger(POSITION_MAGIC) == InpMagicNumber &&
            PositionGetString(POSITION_SYMBOL) == _Symbol &&
            PositionGetInteger(POSITION_TYPE) == posType)
         {
            count++;
         }
      }
   }
   return count;
}

//+------------------------------------------------------------------+
//| Open Buy Position                                                  |
//+------------------------------------------------------------------+
bool OpenBuy(double lots, double sl = 0, double tp = 0)
{
   //--- Pre-trade margin check
   double askCheck = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double marginRequired = 0;
   if(OrderCalcMargin(ORDER_TYPE_BUY, _Symbol, lots, askCheck, marginRequired))
   {
      if(marginRequired > AccountInfoDouble(ACCOUNT_MARGIN_FREE))
      {
         Print("OpenBuy: insufficient margin. Required: ", DoubleToString(marginRequired, 2),
               " Free: ", DoubleToString(AccountInfoDouble(ACCOUNT_MARGIN_FREE), 2));
         return false;
      }
   }

   int retries = 3;
   for(int attempt = 0; attempt < retries; attempt++)
   {
      double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      double slPrice = (sl > 0) ? NormalizeDouble(ask - sl * _Point, _Digits) : 0;
      double tpPrice = (tp > 0) ? NormalizeDouble(ask + tp * _Point, _Digits) : 0;

      if(trade.Buy(lots, _Symbol, ask, slPrice, tpPrice, InpTradeComment))
         return true;

      uint resultCode = trade.ResultRetcode();
      //--- Retryable errors
      if(resultCode == TRADE_RETCODE_REQUOTE || resultCode == TRADE_RETCODE_PRICE_OFF
         || resultCode == TRADE_RETCODE_CONNECTION)
      {
         Print("OpenBuy retry ", attempt + 1, "/", retries, ": ", trade.ResultRetcodeDescription());
         Sleep(200 * (attempt + 1));
         continue;
      }
      //--- Non-retryable errors
      if(resultCode == TRADE_RETCODE_NO_MONEY)
         Print("OpenBuy: insufficient funds for ", DoubleToString(lots, 2), " lots");
      else if(resultCode == TRADE_RETCODE_INVALID_VOLUME)
         Print("OpenBuy: invalid volume ", DoubleToString(lots, 2),
               " (min=", DoubleToString(SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN), 2),
               " max=", DoubleToString(SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX), 2), ")");
      else
         Print("OpenBuy failed: ", trade.ResultRetcodeDescription(), " (code: ", resultCode, ")");
      return false;
   }
   Print("OpenBuy failed after ", retries, " retries");
   return false;
}

//+------------------------------------------------------------------+
//| Open Sell Position                                                 |
//+------------------------------------------------------------------+
bool OpenSell(double lots, double sl = 0, double tp = 0)
{
   //--- Pre-trade margin check
   double bidCheck = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double marginRequired = 0;
   if(OrderCalcMargin(ORDER_TYPE_SELL, _Symbol, lots, bidCheck, marginRequired))
   {
      if(marginRequired > AccountInfoDouble(ACCOUNT_MARGIN_FREE))
      {
         Print("OpenSell: insufficient margin. Required: ", DoubleToString(marginRequired, 2),
               " Free: ", DoubleToString(AccountInfoDouble(ACCOUNT_MARGIN_FREE), 2));
         return false;
      }
   }

   int retries = 3;
   for(int attempt = 0; attempt < retries; attempt++)
   {
      double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      double slPrice = (sl > 0) ? NormalizeDouble(bid + sl * _Point, _Digits) : 0;
      double tpPrice = (tp > 0) ? NormalizeDouble(bid - tp * _Point, _Digits) : 0;

      if(trade.Sell(lots, _Symbol, bid, slPrice, tpPrice, InpTradeComment))
         return true;

      uint resultCode = trade.ResultRetcode();
      //--- Retryable errors
      if(resultCode == TRADE_RETCODE_REQUOTE || resultCode == TRADE_RETCODE_PRICE_OFF
         || resultCode == TRADE_RETCODE_CONNECTION)
      {
         Print("OpenSell retry ", attempt + 1, "/", retries, ": ", trade.ResultRetcodeDescription());
         Sleep(200 * (attempt + 1));
         continue;
      }
      //--- Non-retryable errors
      if(resultCode == TRADE_RETCODE_NO_MONEY)
         Print("OpenSell: insufficient funds for ", DoubleToString(lots, 2), " lots");
      else if(resultCode == TRADE_RETCODE_INVALID_VOLUME)
         Print("OpenSell: invalid volume ", DoubleToString(lots, 2),
               " (min=", DoubleToString(SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN), 2),
               " max=", DoubleToString(SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX), 2), ")");
      else
         Print("OpenSell failed: ", trade.ResultRetcodeDescription(), " (code: ", resultCode, ")");
      return false;
   }
   Print("OpenSell failed after ", retries, " retries");
   return false;
}

//+------------------------------------------------------------------+
//| Close All Positions                                                |
//+------------------------------------------------------------------+
void CloseAllPositions()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
      {
         if(PositionGetInteger(POSITION_MAGIC) == InpMagicNumber &&
            PositionGetString(POSITION_SYMBOL) == _Symbol)
         {
            trade.PositionClose(ticket);
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Close Buy Positions                                                |
//+------------------------------------------------------------------+
void CloseBuyPositions()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
      {
         if(PositionGetInteger(POSITION_MAGIC) == InpMagicNumber &&
            PositionGetString(POSITION_SYMBOL) == _Symbol &&
            PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY)
         {
            trade.PositionClose(ticket);
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Close Sell Positions                                               |
//+------------------------------------------------------------------+
void CloseSellPositions()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
      {
         if(PositionGetInteger(POSITION_MAGIC) == InpMagicNumber &&
            PositionGetString(POSITION_SYMBOL) == _Symbol &&
            PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_SELL)
         {
            trade.PositionClose(ticket);
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Calculate Lot Size based on Risk Percentage                        |
//| Note: slPips parameter is in POINTS (not pips).                    |
//| All SL methods produce point values.                               |
//+------------------------------------------------------------------+
double CalculateLotSize(double riskPercent, double slPips)
{
   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   if(slPips <= 0)
   {
      Print("WARNING: CalculateLotSize called with slPips=0, using minimum lot. Check SL configuration.");
      return minLot;
   }

   if(minLot <= 0)
   {
      Print("WARNING: SYMBOL_VOLUME_MIN is 0 for ", _Symbol, ", defaulting to 0.01");
      minLot = 0.01;
   }

   double balance = InpUseEquityForRisk ? AccountInfoDouble(ACCOUNT_EQUITY) : AccountInfoDouble(ACCOUNT_BALANCE);
   if(balance <= 0)
   {
      Print("WARNING: Account balance/equity is 0, using minimum lot.");
      return minLot;
   }

   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);

   double pipValue = (tickSize > 0) ? tickValue * (_Point / tickSize) : 0;
   if(pipValue <= 0)
   {
      Print("WARNING: Pip value is 0 (tickValue=", DoubleToString(tickValue, 8),
            " tickSize=", DoubleToString(tickSize, 8), "), using minimum lot.");
      return minLot;
   }

   double riskAmount = balance * riskPercent / 100.0;
   double lots = riskAmount / (slPips * pipValue);

   //--- Normalize lot size
   lots = MathFloor(lots / lotStep) * lotStep;
   lots = MathMax(minLot, MathMin(maxLot, lots));
   int lotDigits = (int)MathMax(-MathLog10(lotStep), 0);

   return NormalizeDouble(lots, lotDigits);
}

//+------------------------------------------------------------------+
//| Epsilon-safe double comparisons                                    |
//+------------------------------------------------------------------+
bool DoubleGT(double a, double b)  { return (a - b) >  1e-10; }
bool DoubleLT(double a, double b)  { return (b - a) >  1e-10; }
bool DoubleGE(double a, double b)  { return (a - b) > -1e-10; }
bool DoubleLE(double a, double b)  { return (b - a) > -1e-10; }

//+------------------------------------------------------------------+
//| Log message to both Journal and file                              |
//+------------------------------------------------------------------+
void LogToFile(string message)
{
   Print(message);
   static int logHandle = INVALID_HANDLE;
   static string logFileName = "";
   if(logHandle == INVALID_HANDLE)
   {
      logFileName = "EA_" + IntegerToString(InpMagicNumber) + "_" + _Symbol + ".log";
      logHandle = FileOpen(logFileName, FILE_WRITE|FILE_READ|FILE_TXT|FILE_COMMON);
      if(logHandle == INVALID_HANDLE) return;
      FileSeek(logHandle, 0, SEEK_END);
   }
   string timestamp = TimeToString(TimeCurrent(), TIME_DATE|TIME_MINUTES|TIME_SECONDS);
   FileWriteString(logHandle, timestamp + " | " + message + "\\n");
   FileFlush(logHandle);
}

//+------------------------------------------------------------------+
//| Display strategy overlay on chart (subtle info labels)            |
//+------------------------------------------------------------------+
void ShowStrategyOverlay()
{
   string prefix = "AS_Info_";
   int fontSize = 8;
   color headerClr = C'140,140,160';  // muted slate for header
   color lineClr   = C'100,100,120';  // dimmer for detail lines
   int x = 12;
   int y = 24;
   int lineH = 14;
   int row = 0;

   //--- Header: strategy name
   CreateOverlayLabel(prefix + "0", x, y, InpStrategyDescription, "Consolas", fontSize + 1, headerClr);
   row++;

   //--- Strategy detail lines
   for(int i = 0; i < ArraySize(g_strategyInfo); i++)
   {
      CreateOverlayLabel(prefix + IntegerToString(row), x, y + row * lineH, g_strategyInfo[i], "Consolas", fontSize, lineClr);
      row++;
   }

   //--- Footer: magic | symbol | timeframe
   string footer = "Magic: " + IntegerToString(InpMagicNumber) + "  |  " + _Symbol + " " + EnumToString(Period());
   CreateOverlayLabel(prefix + IntegerToString(row), x, y + row * lineH, footer, "Consolas", fontSize, lineClr);
}

void CreateOverlayLabel(string name, int xDist, int yDist, string text, string font, int size, color clr)
{
   if(ObjectFind(0, name) < 0)
      ObjectCreate(0, name, OBJ_LABEL, 0, 0, 0);
   ObjectSetInteger(0, name, OBJPROP_CORNER, CORNER_LEFT_UPPER);
   ObjectSetInteger(0, name, OBJPROP_XDISTANCE, xDist);
   ObjectSetInteger(0, name, OBJPROP_YDISTANCE, yDist);
   ObjectSetString(0, name, OBJPROP_TEXT, text);
   ObjectSetString(0, name, OBJPROP_FONT, font);
   ObjectSetInteger(0, name, OBJPROP_FONTSIZE, size);
   ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
   ObjectSetInteger(0, name, OBJPROP_SELECTABLE, false);
   ObjectSetInteger(0, name, OBJPROP_HIDDEN, true);
}

`;
}
